import moment from "moment";
import { EventI } from "~/types/EventI";

export const sampleEvents: EventI[] = [
  {
    id: "1",
    title: "Golf with John",
    startDateTime: moment("2023-09-24 09:00:00").toDate(),
    endDateTime: moment("2023-09-24 10:00:00").toDate(),
    location: "Golf Course",
    notes: "John is a great guy",
    relatedConnections: [
      {
        name: "John Doe",
        photoUrl: "https://xsgames.co/randomusers/assets/avatars/male/23.jpg",
        email: "john.doe@example.com",
        tags: [],
      },
    ],
    colour: "blue",
  },
  {
    id: "2",
    title: "Buy Gongcha",
    startDateTime: moment("2023-09-29 10:00:00").toDate(),
    endDateTime: moment("2023-09-29 12:00:00").toDate(),
    location: "Gongcha",
    notes: "Get the milk tea with pearls",
    relatedConnections: [],
    colour: "red",
  },
  {
    id: "3",
    title: "Dinner with Jane",
    startDateTime: moment("2023-09-29 18:00:00").toDate(),
    endDateTime: moment("2023-09-29 20:00:00").toDate(),
    location: "Jane's House",
    notes: "Jane is a great cook",
    relatedConnections: [
      {
        name: "Jane Doe",
        email: "jane@example.com",
        tags: [],
      },
    ],
    colour: "green",
  },
  {
    id: "4",
    title: "Overnight event",
    startDateTime: moment("2023-09-24 22:00:00").toDate(),
    endDateTime: moment("2023-09-25 08:00:00").toDate(),
    location: "My House",
    notes: "Bring sleeping bag",
    relatedConnections: [],
    colour: "purple",
  },
  {
    id: "5",
    title: "Multi-day event",
    startDateTime: moment("2023-09-25 22:00:00").toDate(),
    endDateTime: moment("2023-09-28 08:00:00").toDate(),
    location: "My House",
    notes: "Bring sleeping bag",
    relatedConnections: [],
    colour: "orange",
  },
  {
    id: "6",
    title: "Meeting with boss",
    startDateTime: moment("2023-09-26 09:00:00").toDate(),
    endDateTime: moment("2023-09-26 10:00:00").toDate(),
    location: "Office",
    notes: "Bring laptop",
    relatedConnections: [],
    colour: "blue",
  },
  {
    id: "7",
    title: "Standup meeting",
    startDateTime: moment("2023-10-01 10:00:00").toDate(),
    endDateTime: moment("2023-10-01 10:30:00").toDate(),
    location: "Office",
    notes: "Bring laptop",
    relatedConnections: [],
    colour: "blue",
  },
  {
    id: "8",
    title: "Lunch with friends",
    startDateTime: moment("2023-09-29 12:00:00").toDate(),
    endDateTime: moment("2023-09-29 13:00:00").toDate(),
    location: "Restaurant",
    notes: "",
    relatedConnections: [],
    colour: "yellow",
  },
  {
    id: "9",
    title: "Multi-week event",
    startDateTime: moment("2023-09-29 12:00:00").toDate(),
    endDateTime: moment("2023-10-29 13:00:00").toDate(),
    location: "Restaurant",
    notes: "",
    relatedConnections: [],
    colour: "pink",
  },
];
